import { withWebComponent, WithWebComponentPropTypes } from '@ui5/webcomponents-react/lib/withWebComponent';
import '@ui5/webcomponents/dist/Timeline';
import { FC, ReactNode } from 'react';

export interface TimelinePropTypes extends WithWebComponentPropTypes {
  /**
   * Determines the content of the `Timeline`.
   */
  children?: ReactNode | ReactNode[];
}

/**
 * The `Timeline` component shows entries (such as objects, events, or posts) in chronological order. A common use case is to provide information about changes to an object, or events related to an object. These entries can be generated by the system (for example, value XY changed from A to B), or added manually. There are two distinct variants of the timeline: basic and social. The basic timeline is read-only, while the social timeline offers a high level of interaction and collaboration, and is integrated within SAP Jam
 *
 * <a href="https://sap.github.io/ui5-webcomponents/playground/components/Timeline" target="_blank">UI5 Web Components Playground</a>
 */
const Timeline: FC<TimelinePropTypes> = withWebComponent<TimelinePropTypes>('ui5-timeline', [], [], [], []);

Timeline.displayName = 'Timeline';

Timeline.defaultProps = {};

export { Timeline };
