'use client';

import '@ui5/webcomponents-fiori/dist/Timeline.js';
import type { ReactNode } from 'react';
import { TimelineLayout } from '../../enums/index.js';
import type { CommonProps, Ui5DomRef } from '../../interfaces/index.js';
import { withWebComponent } from '../../internal/withWebComponent.js';

interface TimelineAttributes {
  /**
   * Defines the accessible ARIA name of the component.
   */
  accessibleName?: string;
  /**
   * Defines the items orientation.
   *
   * **Note:** Available options are:
   *
   * *   `Vertical`
   * *   `Horizontal`
   */
  layout?: TimelineLayout | keyof typeof TimelineLayout;
}

export interface TimelineDomRef extends TimelineAttributes, Ui5DomRef {}

export interface TimelinePropTypes extends TimelineAttributes, CommonProps {
  /**
   * Determines the content of the `Timeline`.
   */
  children?: ReactNode | ReactNode[];
}

/**
 * The `Timeline` component shows entries (such as objects, events, or posts) in chronological order. A common use case is to provide information about changes to an object, or events related to an object. These entries can be generated by the system (for example, value XY changed from A to B), or added manually. There are two distinct variants of the timeline: basic and social. The basic timeline is read-only, while the social timeline offers a high level of interaction and collaboration, and is integrated within SAP Jam
 *
 * __Note:__ This component is a web component developed by the UI5 Web Components’ team.
 *
 * <ui5-link href="https://sap.github.io/ui5-webcomponents/playground/?path=/docs/fiori-Timeline" target="_blank">UI5 Web Components Storybook</ui5-link>
 */
const Timeline = withWebComponent<TimelinePropTypes, TimelineDomRef>(
  'ui5-timeline',
  ['accessibleName', 'layout'],
  [],
  [],
  [],
  () => import('@ui5/webcomponents-fiori/dist/Timeline.js')
);

Timeline.displayName = 'Timeline';

Timeline.defaultProps = {
  layout: TimelineLayout.Vertical
};

export { Timeline };
