name: Bug Report
description: File a bug report
title: '[Component Name]:'
labels:
  - bug
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: 'Describe the bug'
      description: 'A clear and concise description of what the bug is.'
    validations:
      required: true
  - type: input
    id: example
    attributes:
      label: 'Isolated Example'
      description: 'Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).'
    validations:
      required: false
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: 'How do you trigger this bug? Please walk us through it step by step.'
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: false
  - type: textarea
    id: expectation
    attributes:
      label: 'Expected Behaviour'
      description: 'A clear and concise description of what you expected to happen.'
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: 'Screenshots'
      description: 'If applicable, add screenshots to help explain your problem.'
    validations:
      required: false


  - type: markdown
    attributes:
      value: '### Environment Info'
  - type: input
    id: wcr-version
    attributes:
      label: 'UI5 Web Components for React Version'
    validations:
      required: true
  - type: input
    id: wc-version
    attributes:
      label: 'UI5 Web Components Version'
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: 'Browser'
      multiple: true
      options:
        - Chrome
        - Edge
        - Firefox
        - Safari
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: 'Operating System'
    validations:
      required: false
      
  - type: markdown
    attributes:
      value: '### Additional Information'
  - type: textarea
    id: additonal-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
