name: Feature Request
description: Suggest an idea for this project
labels:
  - feature-request
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.

  - type: input
    id: org
    attributes:
      label: Organization
      description: Add your organization name.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Privacy Policy
        Please don't disclose any internal or sensitive information like: internal urls, login credentials, screenshots of applications or features in development.
        This is a public GitHub repository and all the information is publicly available.
  - type: checkboxes
    id: confirmation
    attributes:
      label: Declaration
      description: By submitting this issue, I confirm to follow the recommendation not to disclose any internal or sensitive information.
      options:
        - label: I’m not disclosing any internal or sensitive information.
    validations:
      required: true
