export enum SearchFunctions {
  CONTAINS_IGNORE_CASE = 'CONTAINS_IGNORE_CASE',
  CONTAINS_WORD_STARTING_WITH = 'CONTAINS_WORD_STARTING_WITH',
  STARTS_WITH_CASE_SENSITIVE = 'STARTS_WITH_CASE_SENSITIVE'
}
