export const PRIVATE_COMPONENTS = {
  CalendarHeader: true,
  CalendarPart: true,
  DefaultTheme: true,
  DayPicker: true,
  DateComponentBase: true,
  ListItem: true,
  ListItemBase: true,
  MessageBundleAssets: true,
  MonthPicker: true,
  NotificationListItemBase: true,
  Popup: true,
  PickerBase: true,
  SliderBase: true,
  TabBase: true,
  ThemePropertiesProvider: true,
  TimePickerBase: true,
  TreeListItem: true,
  YearPicker: true,
  WheelSlider: true
};

export const COMPONENTS_WITHOUT_DEMOS = {
  ...PRIVATE_COMPONENTS,
  BreadcrumbsItem: 'Breadcrumbs',
  CalendarDate: 'Calendar',
  CardHeader: 'Card',
  CustomListItem: 'List',
  ColorPaletteItem: 'ColorPalette',
  ComboBoxItem: 'ComboBox',
  ComboBoxGroupItem: 'ComboBox',
  FilterItem: 'ViewSettingsDialog',
  FilterItemOption: 'ViewSettingsDialog',
  GroupHeaderListItem: 'List',
  Option: 'Select',
  ShellBarItem: 'ShellBar',
  StandardListItem: 'List',
  SegmentedButtonItem: 'SegmentedButton',
  Tab: 'TabContainer',
  TableCell: 'Table',
  TableColumn: 'Table',
  TableGroupRow: 'Table',
  TableRow: 'Table',
  TabSeparator: 'TabContainer',
  TimelineItem: 'Timeline',
  TreeItem: 'Tree',
  ProductSwitchItem: 'ProductSwitch',
  MediaGalleryItem: 'MediaGallery',
  MultiComboBoxItem: 'MultiComboBox',
  MultiComboBoxGroupItem: 'MultiComboBox',
  SideNavigationItem: 'SideNavigation',
  SideNavigationSubItem: 'SideNavigation',
  SortItem: 'ViewSettingsDialog',
  SuggestionItem: 'Input',
  SuggestionGroupItem: 'Input',
  UploadCollectionItem: 'UploadCollection',
  NotificationAction: 'NotificationListItem',
  WizardStep: 'Wizard',
  MenuItem: 'Menu'
};

export const KNOWN_EVENTS = new Set(['click', 'input', 'submit', 'change', 'select', 'drop']);
export const KNOWN_ATTRIBUTES = new Set(['draggable', 'color']);
