name: Issues Automation

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add new issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/SAP/projects/29
          github-token: ${{ secrets.ACCESS_TOKEN }}
