name: Open Source Security

on:
  push:
    branches:
      - main
  schedule:
    - cron: '12 3 * * *'
  workflow_dispatch:

jobs:
  piper-oss:
    name: 'Security'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: artifactPrepareVersion
        uses: SAP/project-piper-action@bdd04e90dbab9ca2d5a7dd50886b6bac03888360 # v1.22.1
        with:
          step-name: artifactPrepareVersion
          flags: --versioningType cloud_noTag

      - name: detectExecuteScan
        uses: SAP/project-piper-action@bdd04e90dbab9ca2d5a7dd50886b6bac03888360 # v1.22.1
        with:
          step-name: detectExecuteScan
          flags: '--token ${{ secrets.DETECT_TOKEN }}'
